// Focused recipes are loaded on demand; ordinary questions do not carry them.
export const workflows = {
  compare: `Compare the requested sources or alternatives against the user's actual question.
Read each relevant original source; use read_pdf for saved PDFs and inspect page images when a claim depends on a figure or table. Identify missing access rather than filling gaps.
Use consistent comparison dimensions. Keep the visible table to 3–4 concise columns; split a wide matrix into smaller tables. Include source/page references beside claims. Explain material disagreements, differences in evidence or scope, and uncertainty. Do not invent confidence scores or treat separate summaries of one study as independent evidence.
Lead with the useful distinction or recommendation and the criterion behind it, then show the comparison. Explain which differences change the conclusion. Use a chart only for comparable quantitative data with matching units and stated assumptions. Preserve source IDs for save_visual. Run check_presentation on the final Markdown and fix formatting issues before sending. Save topic notes only if asked.`,
  critique: `Review the claim, paper, or proposal on its own terms before judging it.
Inspect the underlying source, relevant methods, figures, data or linked code that the available tools can access. Separate what was verified from what remains untested. Identify the central claim, strongest evidence, assumptions, plausible alternative explanations, and the consequences of limitations.
Prioritize material concerns by their impact on the conclusion. Anchor each concern to a passage or PDF page and describe the evidence that would resolve it. A limitation is not automatically a fatal flaw. Acknowledge strengths and avoid manufacturing an objection to fill a template.
Lead with the most consequential finding and explain how it affects the conclusion. Use concise supporting evidence; a list of methodological terms alone is not an explanation. If a table or diagram improves understanding, run check_presentation before sending and repair reported layout problems. The host handles any Deep evidence review; do not start another investigation or invent verification.`,
  figures: `Choose a line chart for ordered numeric change, bars for category comparison, scatter for relationships, and Mermaid for a process or structure. Use a table when precise values matter more than shape.
Keep one clear question per visual and explain its takeaway nearby. Do not repeat a chart title as an adjacent heading. Label axes with quantities and units; use concise series names. State transformations, assumptions and uncertainty in the caption; do not invent uncertainty intervals or measurements. Keep a stable color mapping across related charts and distinguish lines by pattern as well as color.
Use the dark Discover renderer. Keep Mermaid diagrams small, prefer top-to-bottom flow in narrow panes, and avoid decorative nodes or long labels. Keep comparison tables to 3–4 columns; split wide tables by topic.
Save charts through save_visual, preserve returned embeds, and retain source references and underlying data. Run check_presentation on the actual answer Markdown. Fix clipped/overlapping labels, unreadable diagram text and table problems; recheck changed content. If live Obsidian checking is unavailable, do not claim the layout was visually verified.`,
};
